// Master permission list. Seeded into the `permissions` table by prisma/seed.js
// and referenced by the `permission` middleware to gate routes.

const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',

  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_EDIT: 'customers.edit',
  CUSTOMERS_DELETE: 'customers.delete',

  SUPPLIERS_VIEW: 'suppliers.view',
  SUPPLIERS_CREATE: 'suppliers.create',
  SUPPLIERS_EDIT: 'suppliers.edit',
  SUPPLIERS_DELETE: 'suppliers.delete',

  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_EDIT: 'products.edit',
  PRODUCTS_DELETE: 'products.delete',

  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_TRANSFER: 'inventory.transfer',

  SALES_VIEW: 'sales.view',
  SALES_CREATE: 'sales.create',
  SALES_EDIT: 'sales.edit',
  SALES_VOID: 'sales.void',

  INVOICES_VIEW: 'invoices.view',
  INVOICES_CREATE: 'invoices.create',
  INVOICES_SEND: 'invoices.send',

  PURCHASES_VIEW: 'purchases.view',
  PURCHASES_CREATE: 'purchases.create',
  PURCHASES_EDIT: 'purchases.edit',

  FINANCE_VIEW: 'finance.view',
  FINANCE_CREATE: 'finance.create',

  ACCOUNTING_VIEW: 'accounting.view',
  ACCOUNTING_CREATE: 'accounting.create',

  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',

  EMPLOYEES_VIEW: 'employees.view',
  EMPLOYEES_CREATE: 'employees.create',
  EMPLOYEES_EDIT: 'employees.edit',
  EMPLOYEES_PAYROLL: 'employees.payroll',

  SETTINGS_VIEW: 'settings.view',
  SETTINGS_EDIT: 'settings.edit',

  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_EDIT: 'users.edit',
  USERS_DELETE: 'users.delete',

  ROLES_MANAGE: 'roles.manage',
  AUDIT_VIEW: 'audit.view',
  API_KEYS_MANAGE: 'api_keys.manage'
}

// Default roles created for every new business on registration.
const SYSTEM_ROLES = {
  OWNER: 'Owner',
  ADMIN: 'Administrator',
  MANAGER: 'Manager',
  CASHIER: 'Cashier',
  ACCOUNTANT: 'Accountant',
  EMPLOYEE: 'Employee',
  VIEWER: 'Viewer'
}

const ROLE_PERMISSIONS = {
  [SYSTEM_ROLES.OWNER]: Object.values(PERMISSIONS),
  [SYSTEM_ROLES.ADMIN]: Object.values(PERMISSIONS),
  [SYSTEM_ROLES.MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.PRODUCTS_VIEW, PERMISSIONS.PRODUCTS_CREATE, PERMISSIONS.PRODUCTS_EDIT,
    PERMISSIONS.SALES_VIEW, PERMISSIONS.SALES_CREATE, PERMISSIONS.SALES_EDIT, PERMISSIONS.SALES_VOID,
    PERMISSIONS.INVOICES_VIEW, PERMISSIONS.INVOICES_CREATE, PERMISSIONS.INVOICES_SEND,
    PERMISSIONS.PURCHASES_VIEW, PERMISSIONS.PURCHASES_CREATE, PERMISSIONS.PURCHASES_EDIT,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.FINANCE_VIEW, PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.EMPLOYEES_VIEW
  ],
  [SYSTEM_ROLES.CASHIER]: [
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.SALES_VIEW, PERMISSIONS.SALES_CREATE, PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE, PERMISSIONS.INVENTORY_VIEW
  ],
  [SYSTEM_ROLES.ACCOUNTANT]: [
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.INVOICES_VIEW, PERMISSIONS.INVOICES_CREATE, PERMISSIONS.INVOICES_SEND,
    PERMISSIONS.PURCHASES_VIEW, PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_CREATE,
    PERMISSIONS.ACCOUNTING_VIEW, PERMISSIONS.ACCOUNTING_CREATE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT
  ],
  [SYSTEM_ROLES.EMPLOYEE]: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.PRODUCTS_VIEW, PERMISSIONS.INVENTORY_VIEW],
  [SYSTEM_ROLES.VIEWER]: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.REPORTS_VIEW]
}

module.exports = { PERMISSIONS, SYSTEM_ROLES, ROLE_PERMISSIONS }
