// Master permission list. Seeded into the `permissions` table by prisma/seed.js
// and referenced by the `permission` middleware to gate routes.

const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: 'dashboard.view',
  DASHBOARD_ANALYTICS: 'dashboard.analytics',

  // Customers
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_EDIT: 'customers.edit',
  CUSTOMERS_DELETE: 'customers.delete',
  CUSTOMERS_IMPORT: 'customers.import',
  CUSTOMERS_EXPORT: 'customers.export',

  // Suppliers
  SUPPLIERS_VIEW: 'suppliers.view',
  SUPPLIERS_CREATE: 'suppliers.create',
  SUPPLIERS_EDIT: 'suppliers.edit',
  SUPPLIERS_DELETE: 'suppliers.delete',

  // Products
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_EDIT: 'products.edit',
  PRODUCTS_DELETE: 'products.delete',
  PRODUCTS_CATEGORIES: 'products.categories',

  // Inventory
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_TRANSFER: 'inventory.transfer',
  INVENTORY_RECEIVE: 'inventory.receive',
  INVENTORY_COUNT: 'inventory.count',
  INVENTORY_ALERTS: 'inventory.alerts',

  // Sales
  SALES_VIEW: 'sales.view',
  SALES_CREATE: 'sales.create',
  SALES_EDIT: 'sales.edit',
  SALES_VOID: 'sales.void',
  SALES_APPROVE: 'sales.approve',
  SALES_DISCOUNT: 'sales.discount',
  SALES_RETURNS: 'sales.returns',

  // Quotations
  QUOTATIONS_VIEW: 'quotations.view',
  QUOTATIONS_CREATE: 'quotations.create',
  QUOTATIONS_EDIT: 'quotations.edit',
  QUOTATIONS_APPROVE: 'quotations.approve',
  QUOTATIONS_CONVERT: 'quotations.convert',

  // Invoices
  INVOICES_VIEW: 'invoices.view',
  INVOICES_CREATE: 'invoices.create',
  INVOICES_EDIT: 'invoices.edit',
  INVOICES_SEND: 'invoices.send',
  INVOICES_DELETE: 'invoices.delete',

  // Purchases
  PURCHASES_VIEW: 'purchases.view',
  PURCHASES_CREATE: 'purchases.create',
  PURCHASES_EDIT: 'purchases.edit',
  PURCHASES_APPROVE: 'purchases.approve',
  PURCHASES_RECEIVE: 'purchases.receive',

  // Payments
  PAYMENTS_VIEW: 'payments.view',
  PAYMENTS_CREATE: 'payments.create',
  PAYMENTS_APPROVE: 'payments.approve',
  PAYMENTS_RECONCILE: 'payments.reconcile',

  // Expenses
  EXPENSES_VIEW: 'expenses.view',
  EXPENSES_CREATE: 'expenses.create',
  EXPENSES_EDIT: 'expenses.edit',
  EXPENSES_APPROVE: 'expenses.approve',
  EXPENSES_DELETE: 'expenses.delete',

  // Finance
  FINANCE_VIEW: 'finance.view',
  FINANCE_CREATE: 'finance.create',
  FINANCE_APPROVE: 'finance.approve',
  FINANCE_BUDGETS: 'finance.budgets',
  FINANCE_FORECAST: 'finance.forecast',

  // Accounting
  ACCOUNTING_VIEW: 'accounting.view',
  ACCOUNTING_CREATE: 'accounting.create',
  ACCOUNTING_JOURNALS: 'accounting.journals',
  ACCOUNTING_RECONCILE: 'accounting.reconcile',
  ACCOUNTING_CLOSE_PERIOD: 'accounting.close_period',

  // Reports
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',
  REPORTS_FINANCIAL: 'reports.financial',
  REPORTS_SALES: 'reports.sales',
  REPORTS_INVENTORY: 'reports.inventory',
  REPORTS_CUSTOM: 'reports.custom',

  // Employees
  EMPLOYEES_VIEW: 'employees.view',
  EMPLOYEES_CREATE: 'employees.create',
  EMPLOYEES_EDIT: 'employees.edit',
  EMPLOYEES_DELETE: 'employees.delete',
  EMPLOYEES_PAYROLL: 'employees.payroll',
  EMPLOYEES_ATTENDANCE: 'employees.attendance',
  EMPLOYEES_PERFORMANCE: 'employees.performance',
  EMPLOYEES_LEAVE: 'employees.leave',

  // HR Management
  HR_RECRUITMENT: 'hr.recruitment',
  HR_ONBOARDING: 'hr.onboarding',
  HR_TRAINING: 'hr.training',
  HR_POLICIES: 'hr.policies',

  // Branches
  BRANCHES_VIEW: 'branches.view',
  BRANCHES_CREATE: 'branches.create',
  BRANCHES_EDIT: 'branches.edit',
  BRANCHES_DELETE: 'branches.delete',

  // Warehouses
  WAREHOUSES_VIEW: 'warehouses.view',
  WAREHOUSES_MANAGE: 'warehouses.manage',
  WAREHOUSES_DISPATCH: 'warehouses.dispatch',

  // Projects
  PROJECTS_VIEW: 'projects.view',
  PROJECTS_CREATE: 'projects.create',
  PROJECTS_EDIT: 'projects.edit',
  PROJECTS_ASSIGN: 'projects.assign',
  PROJECTS_REPORTS: 'projects.reports',

  // Tasks
  TASKS_VIEW: 'tasks.view',
  TASKS_CREATE: 'tasks.create',
  TASKS_EDIT: 'tasks.edit',
  TASKS_ASSIGN: 'tasks.assign',

  // Support
  SUPPORT_VIEW: 'support.view',
  SUPPORT_CREATE: 'support.create',
  SUPPORT_RESPOND: 'support.respond',
  SUPPORT_ESCALATE: 'support.escalate',
  SUPPORT_CLOSE: 'support.close',

  // Marketing
  MARKETING_CAMPAIGNS: 'marketing.campaigns',
  MARKETING_PROMOTIONS: 'marketing.promotions',
  MARKETING_LOYALTY: 'marketing.loyalty',
  MARKETING_ANALYTICS: 'marketing.analytics',

  // Deliveries
  DELIVERIES_VIEW: 'deliveries.view',
  DELIVERIES_ASSIGN: 'deliveries.assign',
  DELIVERIES_UPDATE: 'deliveries.update',
  DELIVERIES_COMPLETE: 'deliveries.complete',

  // Settings
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_EDIT: 'settings.edit',
  SETTINGS_BUSINESS: 'settings.business',
  SETTINGS_TAX: 'settings.tax',
  SETTINGS_PAYMENT: 'settings.payment',

  // Users
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_EDIT: 'users.edit',
  USERS_DELETE: 'users.delete',
  USERS_INVITE: 'users.invite',

  // Roles & Permissions
  ROLES_VIEW: 'roles.view',
  ROLES_MANAGE: 'roles.manage',
  PERMISSIONS_MANAGE: 'permissions.manage',

  // Subscription
  SUBSCRIPTION_VIEW: 'subscription.view',
  SUBSCRIPTION_MANAGE: 'subscription.manage',

  // Audit & Security
  AUDIT_VIEW: 'audit.view',
  AUDIT_EXPORT: 'audit.export',
  SECURITY_MANAGE: 'security.manage',

  // API & Integrations
  API_KEYS_VIEW: 'api_keys.view',
  API_KEYS_MANAGE: 'api_keys.manage',
  INTEGRATIONS_VIEW: 'integrations.view',
  INTEGRATIONS_MANAGE: 'integrations.manage',
  WEBHOOKS_MANAGE: 'webhooks.manage',

  // System Admin (Super Admin only)
  SYSTEM_TENANTS: 'system.tenants',
  SYSTEM_PLANS: 'system.plans',
  SYSTEM_HEALTH: 'system.health',
  SYSTEM_BACKUPS: 'system.backups',
  SYSTEM_ANALYTICS: 'system.analytics',

  // Self-service (all users)
  SELF_PROFILE: 'self.profile',
  SELF_PASSWORD: 'self.password',
  SELF_PAYSLIP: 'self.payslip',
  SELF_LEAVE: 'self.leave',
  SELF_ATTENDANCE: 'self.attendance',
  SELF_EXPENSES: 'self.expenses'
}

// Enterprise role definitions
const ENTERPRISE_ROLES = {
  // System Level
  SUPER_ADMIN: 'Super Administrator',
  
  // Business Level
  BUSINESS_OWNER: 'Business Owner',
  BRANCH_MANAGER: 'Branch Manager',
  OPERATIONS_MANAGER: 'Operations Manager',
  
  // Sales
  SALES_MANAGER: 'Sales Manager',
  CASHIER: 'Cashier',
  
  // Inventory & Procurement
  INVENTORY_OFFICER: 'Inventory Officer',
  PROCUREMENT_OFFICER: 'Procurement Officer',
  
  // Finance & Accounting
  ACCOUNTANT: 'Accountant',
  
  // HR
  HR_MANAGER: 'HR Manager'
}

// Permission mappings for each enterprise role
const ENTERPRISE_ROLE_PERMISSIONS = {
  // Super Administrator - Full system access
  [ENTERPRISE_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  
  // Business Owner - Full business access
  [ENTERPRISE_ROLES.BUSINESS_OWNER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_ANALYTICS,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.CUSTOMERS_DELETE,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SUPPLIERS_CREATE,
    PERMISSIONS.SUPPLIERS_EDIT,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_EDIT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_APPROVE,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_APPROVE,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_APPROVE,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.REPORTS_FINANCIAL,
    PERMISSIONS.EMPLOYEES_VIEW,
    PERMISSIONS.BRANCHES_VIEW,
    PERMISSIONS.BRANCHES_CREATE,
    PERMISSIONS.BRANCHES_EDIT,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_EDIT,
    PERMISSIONS.SETTINGS_BUSINESS,
    PERMISSIONS.SETTINGS_TAX,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_INVITE,
    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.SUBSCRIPTION_VIEW,
    PERMISSIONS.SUBSCRIPTION_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.SECURITY_MANAGE
  ],

  // Branch Manager
  [ENTERPRISE_ROLES.BRANCH_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.EMPLOYEES_VIEW,
    PERMISSIONS.EMPLOYEES_EDIT,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_APPROVE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.SUPPORT_RESPOND
  ],

  // Operations Manager
  [ENTERPRISE_ROLES.OPERATIONS_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.PURCHASES_CREATE,
    PERMISSIONS.PURCHASES_APPROVE,
    PERMISSIONS.WAREHOUSES_VIEW,
    PERMISSIONS.WAREHOUSES_MANAGE,
    PERMISSIONS.EMPLOYEES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_INVENTORY
  ],

  // Sales Manager
  [ENTERPRISE_ROLES.SALES_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_APPROVE,
    PERMISSIONS.SALES_DISCOUNT,
    PERMISSIONS.QUOTATIONS_VIEW,
    PERMISSIONS.QUOTATIONS_APPROVE,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_SALES,
    PERMISSIONS.EMPLOYEES_VIEW
  ],

  // Sales Representative
  [ENTERPRISE_ROLES.SALES_REP]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_RETURNS,
    PERMISSIONS.QUOTATIONS_VIEW,
    PERMISSIONS.QUOTATIONS_CREATE,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.PRODUCTS_VIEW
  ],

  // Cashier
  [ENTERPRISE_ROLES.CASHIER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_RETURNS,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.INVENTORY_VIEW
  ],

  // Inventory Officer
  [ENTERPRISE_ROLES.INVENTORY_OFFICER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.INVENTORY_RECEIVE,
    PERMISSIONS.INVENTORY_COUNT,
    PERMISSIONS.WAREHOUSES_VIEW,
    PERMISSIONS.WAREHOUSES_MANAGE,
    PERMISSIONS.WAREHOUSES_DISPATCH,
    PERMISSIONS.PURCHASES_RECEIVE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_INVENTORY
  ],

  // Procurement Officer
  [ENTERPRISE_ROLES.PROCUREMENT_OFFICER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SUPPLIERS_CREATE,
    PERMISSIONS.SUPPLIERS_EDIT,
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.PURCHASES_CREATE,
    PERMISSIONS.PURCHASES_EDIT,
    PERMISSIONS.QUOTATIONS_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.REPORTS_VIEW
  ],

  // Accountant
  [ENTERPRISE_ROLES.ACCOUNTANT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.INVOICES_SEND,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_APPROVE,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.EXPENSES_APPROVE,
    PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.ACCOUNTING_CREATE,
    PERMISSIONS.ACCOUNTING_JOURNALS,
    PERMISSIONS.ACCOUNTING_RECONCILE,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE,
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.FINANCE_BUDGETS,
    PERMISSIONS.FINANCE_FORECAST,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.REPORTS_FINANCIAL
  ],

  // HR Manager
  [ENTERPRISE_ROLES.HR_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.EMPLOYEES_VIEW,
    PERMISSIONS.EMPLOYEES_CREATE,
    PERMISSIONS.EMPLOYEES_EDIT,
    PERMISSIONS.EMPLOYEES_DELETE,
    PERMISSIONS.EMPLOYEES_PAYROLL,
    PERMISSIONS.EMPLOYEES_ATTENDANCE,
    PERMISSIONS.EMPLOYEES_PERFORMANCE,
    PERMISSIONS.EMPLOYEES_LEAVE,
    PERMISSIONS.HR_RECRUITMENT,
    PERMISSIONS.HR_ONBOARDING,
    PERMISSIONS.HR_TRAINING,
    PERMISSIONS.HR_POLICIES,
    PERMISSIONS.REPORTS_VIEW
  ]
}

module.exports = { 
  PERMISSIONS, 
  ENTERPRISE_ROLES,
  ENTERPRISE_ROLE_PERMISSIONS
}
